apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng
spec:
  selector:
    matchLabels:
      app: stress-ng
  replicas: 2
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: stress-ng
          image: armanmollaei/trust:100
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              cd /tmp && stress-ng --cpu 4 --timeout 16000 --metrics-brief && sleep 3600000
